version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports: 
      - 5432:5432
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  db_data:

